services:
  minecraft:
    image: "towinok/purpur:1.20.1"
    restart: always
    container_name: "purpur"
    environment:
      MEMORYSIZE: "12G"
      #G1GC
      #JAVAFLAGS: "-Dterminal.jline=false -Dterminal.ansi=true -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=170 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=50 -XX:G1HeapRegionSize=32M -XX:G1ReservePercent=15 -XX:InitiatingHeapOccupancyPercent=20 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -Dcom.mojang.eula.agree=true"
      #ZGC
      JAVAFLAGS: "-Djava.awt.headless=true -Dterminal.jline=false -Dterminal.ansi=true -XX:+UseZGC -XX:ConcGCThreads=8 -XX:MaxGCPauseMillis=20 -XX:ActiveProcessorCount=8 -XX:+UseNUMA -XX:+AlwaysPreTouch -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled  -XX:+PerfDisableSharedMem -XX:InitiatingHeapOccupancyPercent=20  -Dcom.mojang.eula.agree=true"
      #PURPUR_FLAGS:
      #OVERRIDEFLAGS:    
    cpus: 8.0
    mem_limit: 14746M
    memswap_limit: 14746M
    volumes:
      - "/mnt/nvme1/purpur_main:/data:rw"
    ports:
    #main
      - "25565:25565/tcp"
    #for Raknetify
      - "25565:25565/udp"
    #voice
      - "24454:24454/udp"
    # The following allow `docker attach minecraft` to work
    stdin_open: true
    tty: true
    depends_on:
      - db
      - adminer
