version: "3"
#stop using root as default... Just set up bases as root and use only user account!
services:
  minecraft:
    image: "towinok/purpurmain:latest"
    restart: always
    container_name: "purpur"
    environment:
      MEMORYSIZE: "1G"
    cpus: 8.0
    mem_limit: 14746M
    volumes:
      - "/path/to/purpur_data:/data:rw"
    ports:
      - "25565:25565/tcp"
    stdin_open: true
    tty: true

