name: Build and Publish Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3.2.0

    - name: Get Latest Tag
      id: get-latest-tag
      run: |
        latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
        echo "Latest tag: $latest_tag"
        echo "::set-output name=latest_tag::$latest_tag"

    - name: Build Docker image
      run: docker build -t towinok/purpurmain:forpull .
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: towinok
        password: ${{ secrets.D_TOCKEN }}

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image to GitHub Container Registry
      run: |
        docker tag towinok/purpurmain:forpull towinok/purpurmain:${{ steps.get-latest-tag.outputs.latest_tag }}
        docker push towinok/purpurmain:${{ steps.get-latest-tag.outputs.latest_tag }}
