name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t towinok/purpurmain:${{ github.sha }} .

   # - name: Log in to GitHub Container Registry
  #  run: echo ${{ secrets.D_TOCKEN}} | docker login ghcr.io -u towinok --password-stdin

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_HUB_USERNAME}}
        password: ${{secrets.D_TOCKEN}}
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.D_TOCKEN}}


    - name: Push Docker image to GitHub Container Registry
      run: docker push ghcr.io/towinok/purpurmain:${{ github.sha }}
